#!/bin/sh -e

echo "---> Installing HTTP configuration..."
cp -Rf /tmp/src/http.conf.d/*.conf /nginx/http.conf.d/

echo "---> Installing STREAM configuration..."
cp -Rf /tmp/src/stream.conf.d/*.conf /nginx/stream.conf.d/

echo "---> Installing html files..."
cp -Rf /tmp/src/html/. /nginx/html/

echo "---> Testing the generated configuration..."
nginx -p /nginx -c /nginx/nginx.conf -t
rm -f /nginx/nginx.pid

echo "---> All done."
